language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
branches:
  only:
    - master
    - develop
script:
  - npm run build
deploy:
  - provider: surge
    project: ./docs/
    domain: docs.upstamps.com
    skip_cleanup: true
    on:
      tags: true